data:
    test_data: /opt/ml/dataset/test/test_data.csv
    
model:
    bin_plm : klue/roberta-base
    sec_plm : klue/roberta-large
    binary_model : /opt/ml/code/best_model/binary/bin_roberta-base
    per_model : /opt/ml/code/best_model/binary/per_roberta-large
    org_model : /opt/ml/code/best_model/binary/org_roberta-large
    model_name: klue/roberta-base
    saved_model: /opt/ml/code/best_model/binary/bin_roberta-base
train:
    seed : 42
test:
    num_to_label: /opt/ml/code/dict_num_to_label.pkl
    output_csv: /opt/ml/code/prediction/23 new_meta_binary.csv