data:
    train_data: /opt/ml/code/for_binary/data/per_train.csv
    shuffle: True
    
model:
    plm : roberta-large
    model_name: klue/roberta-large
    saved_model: /opt/ml/code/best_model/binary/per_roberta-large_ver3
    
train:
    train_mode: True
    seed: 42
    batch_size: 16
    epoch: 15
    lr: 1e-5
    num_workers : 4
    logging_step: 100
    patience : 100
    warmup_steps : 1000
    weight_decay: 0.01
    checkpoint : /opt/ml/code/results
    T_0 : 50
    T_mult : 2
    eta_min : 1e-7


test:
    test_mode: True
    num_to_label: /opt/ml/code/dict_num_to_label.pkl
    output_csv: /opt/ml/code/prediction/19_electra_final.csv

wandb:
    project_name: new_meta_bin_cf
    entity: klue-bora
    exp_name: third_model_per