program: train_OmegaConf_kf.py
method: grid
name: 47_cv
metric:
  goal: maximize
  name: eval/micro_f1_score
parameters:
  model_name:
    values: [klue/roberta-small]
  batch_size: 
    values: [32]
  epochs:
    values: [5]
  lr_type:
    values: [AdamW]
  lr:
    values: [1e-5]
  weight_decay:
    values: [0.01]
