program: train_OmegaConf.py
method: grid
name: 99_klue-sweep-test2
metric:
  goal: maximize
  name: eval/micro_f1_score
parameters:
  model_name:
    values: [klue/roberta-small]
  batch_size: 
    values: [32, 64]
  epochs:
    values: [10]
  lr:
    values: [5e-5]
  weight_decay:
    values: [0.01]