program: train_OmegaConf_cv.py
method: grid
name: 43_scheduler
metric:
  goal: maximize
  name: eval/micro_f1_score
parameters:
  model_name:
    values: [klue/roberta-small]
  batch_size: 
    values: [32, 64]
  epochs:
    values: [10]
  lr_type:
    values: [SGD, AdamW]
  lr:
    values: [2.24E-04, 1e-5]
  weight_decay:
    values: [0.01]
