path:
    train_path: ../dataset/train
    test_path: ../dataset/test
    best_model : ./best_model
    checkpoint : ./results

data:
    shuffle: True
    augmentation: # adea, bt 등등
    
model:
    model_name: klue/bert-base
    saved_name: base-line
    exp_name : devSplit

train:
    seed: 42
    batch_size: 16
    epoch: 10
    lr : 5e-5
    eval_step: 500
    # patience : 10

test:
    save_name : bert-base/devSplit