path:
    train_path: ../dataset/train
    test_path: ../dataset/test/test_data
    best_model : ./best_model
    checkpoint : ./results

data:
    shuffle: True
    augmentation: # adea, bt 등등
    
model:
    model_name: klue/roberta-large
    saved_name: roberta_large_fix_text_lr7_6_split_staritify
    exp_name : roberta-large fix_text lr7e-6 split_staritify

train:
    seed: 42
    batch_size: 32
    epoch: 30
    lr : 3e-6
    logging_step: 1000
    patience : 10

test:
    save_name : submission_roberta_large_fix_text_lr7_6_split_staritify