data:
    train_data: /opt/ml/dataset/train/train.csv
    test_data: /opt/ml/dataset/test/test_data.csv
    shuffle: True
    
model:
    plm : BERT
    model_name: klue/roberta-large
    saved_model: /opt/ml/code/best_model/rbert/rbert_IRE_v3.pt
    # saved_model : /opt/ml/code/best_model/electra/electra_final_test.pt
    
train:
    train_mode: True
    seed: 42
    batch_size: 32
    epoch: 30
    lr: 3e-5
    num_workers : 4
    logging_step: 100
    patience : 2
    warmup_steps : 1000
    weight_decay: 0.01
    checkpoint : /opt/ml/code/results
    marker_mode : TEM_punct
    entity_embedding : True
    T_0 : 100
    T_mult : 4
    eta_min : 1e-7
    

test:
    test_mode: True
    num_to_label: /opt/ml/code/dict_num_to_label.pkl
    output_csv: /opt/ml/code/prediction/second_test_RBERTa.csv

wandb:
    project_name: klue-roberta-large
    entity: klue-bora
    exp_name: 29 second_test for RBERTa_v3


